'''
Pseudocode: 
def workflow(): 
    1. Calls ask_company_name()
        if ask_company_name() is None, prompts the quit menu.  
    2. Calls resolve_company()
        if resolve_company() calls a CompanyResolverError, prompts Ask another company prompt, send the company resolver error and then ask to input another company. 
        else proceed with ask_yes_no() 
    3. Calls ask_yes_no()
        if ask_yes_no() is "N", prompts ask_company_name() again
        if ask_yes_no() is None, prompts the quit menu
        else proceed with ask_period_type()
    4. Calls ask_period_type()
        if ask_period_type() is None, prompts the quit menu
        else proceed with selected ask_period_count()
    5. Once a period type has been selected, the user will select the number of periods from ask_period_count() 
        if ask_period_count() is None, prompts the quit menu
        else proceed with step 6.
    6. The company ticker, period type, and period count will be sent to YahooClient(ticker).get_available_periods(), then .fetch_all() will be called to fetch all the data.
    7. The data will be sent to their respective parsers in data/parsers/ - all parsers 
    8. An AI summary will be generated by taking in the name of the company and the ticker in the services/openai_client.py file. This will be the summary for export. 
    9. All the parsed data + the AI summary will be sent to the exporter in exporters/excel_exporter.py 
    10. The user will be prompted to export another company via another loop. 
      If the user selects 'Y' then it will restart the def workflow() function 
      If the user selects 'N' then the program will exit.
      If the user selects None then it will prompt the quit menu.


'''
from config.settings import OPENAI_API_KEY, EXPORT_DIR
from ui.prompts import ask_company_name, ask_yes_no, ask_period_type, ask_period_count, quit
from services.company_resolver import resolve_company, CompanyResolverError
from services.yahoo_client import YahooClient
from services.openai_client import get_ai_summary
from data.parsers.company import parse_company
from data.parsers.historical_price import parse_historical_prices
from data.parsers.income_statement import parse_income_statement
from data.parsers.balance_sheet import parse_balance_sheet
from data.parsers.cashflow_statement import parse_cashflow_statement
from data.parsers.financial_ratios import parse_financial_ratios
from exporters.excel_exporter import export

def run():
    """Runs the Company Info Workflow"""

    while True:

        # Keep asking until we have a confirmed company
        while True:

            # Ask for a company
            user_input = ask_company_name("Enter a company name: ")

            if user_input is None:
                if quit():
                    return
                continue

            # Try to resolve the company
            try:
                ticker, company_name = resolve_company(user_input)
            except CompanyResolverError as e:
                print(e.message)
                continue

            # Confirm with the user
            confirmed = ask_yes_no(
                f"Do you want to research {company_name} ({ticker})? (Y/N): "
            )

            if confirmed is True:
                break

            elif confirmed is False:
                continue

            elif confirmed is None:
                if quit():
                    return
                continue

        # Ask for period type
        period_type = ask_period_type(
            "What period type would you like to use? (Annual or Quarterly): "
        )

        if period_type is None:
            if quit():
                break
            continue

        # Ask for number of periods
        period_count = ask_period_count(
            "Enter the number of periods: ",
            period_type,
        )

        if period_count is None:
            if quit():
                break
            continue

        # Fetch the data
        yahoo_client = YahooClient(ticker).fetch_all(period_type, period_count)

        # Parse the data
        parse_company(yahoo_client, company_name, ticker)
        parse_historical_prices(yahoo_client)
        parse_income_statement(yahoo_client)
        parse_balance_sheet(yahoo_client)
        parse_cashflow_statement(yahoo_client)
        parse_financial_ratios(yahoo_client)

        # Generate the AI summary
        ai_summary = get_ai_summary(ticker, company_name)

        # Export the data
        export(EXPORT_DIR, company_name, ticker, ai_summary)

        # Ask if the user wants to research another company
        restart = ask_yes_no(
            "Do you want to research another company? (Y/N): "
        )

        if restart == "Y":
            continue

        elif restart == "N":
            break

        elif restart is None:
            if quit():
                break
            continue